FROM ubuntu:20.04
ENV TZ=Europe
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install --no-install-recommends -y \
  make \
  texlive-latex-extra \
  graphviz \
  doxygen \
&& rm -rf /var/lib/apt/lists/*
