name: basic workflow
on: 
  push

jobs:
  build:
    runs-on: ubuntu-latest
    container: quaranteam1/quaranteam:latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the application
        run: make
      - name: Check g++ version
        run: echo | g++ --version
      - name: Convert files
        run: sed -i 's/\r//g' ./run_test.sh
      - name: Run input-output tests
        run: bash run_test.sh main generated_output.txt
      - name: Check result of input-output tests
        run: diff ./generated_output.txt ./expected_output.txt
      - name: Upload generated output
        uses: actions/upload-artifact@v2
        with:
          name: generated_output
          path: generated_output.txt

  doxygen:
    runs-on: ubuntu-latest
    container: quaranteam1/quaranteam:latest
    steps:
    - uses: actions/checkout@v2
    - run: doxygen doxyconf 
    - name: make pdf from latex
      working-directory:  docs/latex/
      run: make
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: doxygen
        path: docs/

  gtest:
    runs-on: ubuntu-latest
    container: quaranteam1/quaranteam:latest
    steps:
    - uses: actions/checkout@v2
    - name: run cmake and make
      run: cd /usr/src/gtest && cmake CMakeLists.txt && make
    - name: Symbolic links 
      run:  ln -st /usr/lib/ /usr/src/gtest/libgtest.a && ln -st /usr/lib/ /usr/src/gtest/libgtest_main.a
    - name: Make Makefile and run unit tests
      run: cd UnitTests && cmake CMakeLists.txt && make && ./runGTest

  valgrind:
    runs-on: ubuntu-latest
    container: quaranteam1/quaranteam:latest
    steps:
    - uses: actions/checkout@v2
    - name: Make main
      run: make
    - name: Run memcheck
      run: valgrind main