name: Documentation

on: 
  push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install doxygen graphviz texlive
    - run: doxygen doxyconf 
      uses: pdflatex refman.tex
    - name: Push git subdir as a branch
      uses: s0/git-publish-subdir-action@v2.4.0
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: docs/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

   